import json
import threading
import unittest
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from webtest import TestApp

from dtos import STATUS_ERROR, STATUS_OK, IndexResponse, V1ResponseBase
import flaresolverr

# The token is generated by the page itself and only ever reaches the network as
# a query parameter, so a capture that returns it proves the init script ran in
# the same document as the host JS rather than replaying a known URL.
TOKEN_PAGE = """<!doctype html>
<html><head><title>Kani capture fixture</title></head>
<body><div id="out">loading</div>
<script>
  var token = 'tok-' + Math.floor(Math.random() * 1e9);
  window.addEventListener('load', function () {
    setTimeout(function () {
      fetch('/api/data?token=' + encodeURIComponent(token))
        .then(function (r) { return r.json(); })
        .then(function (j) { document.getElementById('out').textContent = j.ok; });
    }, 150);
  });
</script>
</body></html>"""

INIT_SCRIPT = """
var originalFetch = window.fetch;
window.fetch = function (input) {
  var url = typeof input === 'string' ? input : input.url;
  if (url.indexOf('/api/data') !== -1) {
    window.passPayload(JSON.stringify({ url: url }));
  }
  return originalFetch.apply(this, arguments);
};
"""


class _Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path.startswith('/api/data'):
            body = json.dumps({"ok": True}).encode()
            content_type = 'application/json'
        else:
            body = TOKEN_PAGE.encode()
            content_type = 'text/html'
        self.send_response(200)
        self.send_header('Content-Type', content_type)
        self.send_header('Content-Length', str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass


class TestKaniCapture(unittest.TestCase):

    app = TestApp(flaresolverr.app)
    app.get('/')

    @classmethod
    def setUpClass(cls):
        cls.server = ThreadingHTTPServer(('127.0.0.1', 0), _Handler)
        cls.port = cls.server.server_address[1]
        cls.thread = threading.Thread(target=cls.server.serve_forever, daemon=True)
        cls.thread.start()

    @classmethod
    def tearDownClass(cls):
        cls.server.shutdown()
        cls.server.server_close()

    def _url(self, path='/'):
        return f'http://127.0.0.1:{self.port}{path}'

    def test_index_advertises_capability(self):
        body = IndexResponse(self.app.get('/').json)
        self.assertIn('kani.capture/1', body.capabilities)
        self.assertIn('kani.capture/2', body.capabilities)

    def test_capture_returns_page_generated_token(self):
        res = self.app.post_json('/v1', {
            'cmd': 'kani.capture',
            'url': self._url(),
            'initScript': INIT_SCRIPT,
            'maxTimeout': 60000
        })
        self.assertEqual(res.status_code, 200)

        body = V1ResponseBase(res.json)
        self.assertEqual(STATUS_OK, body.status)
        payload = json.loads(body.solution.payload)
        self.assertIn('/api/data?token=tok-', payload['url'])
        self.assertIn('Chrome/', body.solution.userAgent)

    def test_capture_requires_init_script(self):
        res = self.app.post_json('/v1', {
            'cmd': 'kani.capture',
            'url': self._url()
        }, status=500)

        body = V1ResponseBase(res.json)
        self.assertEqual(STATUS_ERROR, body.status)
        self.assertIn("'initScript' is mandatory", body.message)

    def test_capture_requires_url(self):
        res = self.app.post_json('/v1', {
            'cmd': 'kani.capture',
            'initScript': INIT_SCRIPT
        }, status=500)

        body = V1ResponseBase(res.json)
        self.assertEqual(STATUS_ERROR, body.status)
        self.assertIn("'url' is mandatory", body.message)

    def test_capture_reuses_a_session_without_leaking_scripts(self):
        session = 'kani-test-script-cleanup'
        try:
            first = self.app.post_json('/v1', {
                'cmd': 'kani.capture',
                'url': self._url(),
                'initScript': INIT_SCRIPT,
                'session': session,
                'maxTimeout': 60000
            })
            self.assertEqual(STATUS_OK, V1ResponseBase(first.json).status)

            second = self.app.post_json('/v1', {
                'cmd': 'kani.capture',
                'url': self._url(),
                'initScript': 'window.__noop = 1;',
                'session': session,
                'captureTimeout': 1000,
                'maxTimeout': 60000
            }, status=500)
            self.assertIn('passPayload was not called', V1ResponseBase(second.json).message)
        finally:
            self.app.post_json('/v1', {
                'cmd': 'sessions.destroy',
                'session': session
            })

    def test_capture_heartbeat_extends_the_idle_deadline(self):
        script = """
var heartbeat = setInterval(function () { window.resetPayloadTimer(); }, 200);
setTimeout(function () {
  clearInterval(heartbeat);
  window.passPayload('ready');
}, 1400);
"""
        res = self.app.post_json('/v1', {
            'cmd': 'kani.capture',
            'url': self._url(),
            'initScript': script,
            'captureTimeout': 500,
            'maxTimeout': 10000
        })

        body = V1ResponseBase(res.json)
        self.assertEqual(STATUS_OK, body.status)
        self.assertEqual('ready', body.solution.payload)

    def test_capture_times_out_when_payload_never_arrives(self):
        res = self.app.post_json('/v1', {
            'cmd': 'kani.capture',
            'url': self._url(),
            'initScript': 'window.__noop = 1;',
            'captureTimeout': 2000,
            'maxTimeout': 60000
        }, status=500)

        body = V1ResponseBase(res.json)
        self.assertEqual(STATUS_ERROR, body.status)
        self.assertIn('passPayload was not called', body.message)

    def test_capture_enforces_payload_size_limit(self):
        res = self.app.post_json('/v1', {
            'cmd': 'kani.capture',
            'url': self._url(),
            'initScript': "window.passPayload('x'.repeat(4096));",
            'maxPayloadBytes': 1024,
            'maxTimeout': 60000
        }, status=500)

        body = V1ResponseBase(res.json)
        self.assertEqual(STATUS_ERROR, body.status)
        self.assertIn('over the 1024 byte limit', body.message)


if __name__ == '__main__':
    unittest.main()


class TestKaniCaptureAuth(unittest.TestCase):
    """The /v1 gate. Auth is opt-in, so the unset case must stay unchanged."""

    KEY = 'test-secret-key'

    def setUp(self):
        self._previous = flaresolverr.env_api_key

    def tearDown(self):
        flaresolverr.env_api_key = self._previous

    def _app(self, key):
        flaresolverr.env_api_key = key
        return TestApp(flaresolverr.app)

    def test_v1_rejects_a_missing_key(self):
        res = self._app(self.KEY).post_json('/v1', {'cmd': 'sessions.list'}, status=401)
        self.assertEqual(STATUS_ERROR, res.json['status'])
        self.assertIn('X-Api-Key', res.json['message'])

    def test_v1_rejects_a_wrong_key(self):
        res = self._app(self.KEY).post_json(
            '/v1', {'cmd': 'sessions.list'},
            headers={'X-Api-Key': 'wrong'}, status=401)
        self.assertEqual(STATUS_ERROR, res.json['status'])

    def test_v1_accepts_the_right_key(self):
        res = self._app(self.KEY).post_json(
            '/v1', {'cmd': 'sessions.list'}, headers={'X-Api-Key': self.KEY})
        self.assertEqual(STATUS_OK, res.json['status'])

    def test_v1_is_open_when_no_key_is_configured(self):
        res = self._app(None).post_json('/v1', {'cmd': 'sessions.list'})
        self.assertEqual(STATUS_OK, res.json['status'])

    def test_index_and_health_stay_open_when_a_key_is_configured(self):
        app = self._app(self.KEY)
        self.assertIn('kani.capture/2', IndexResponse(app.get('/').json).capabilities)
        self.assertEqual(STATUS_OK, app.get('/health').json['status'])
